import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class authentication extends javax.swing.JFrame {

    /**
     * Creates new form authentication
     */
    int num,ReceiverBalance,SenderBalance,Cre_Amount,temp;
    String User_name,uname,email,currency;
    public String status ; 
    public authentication()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        otpNumber = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Enter the OTP number");

        otpNumber.setBackground(new java.awt.Color(0, 0, 0));
        otpNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        otpNumber.setForeground(new java.awt.Color(255, 255, 255));
        otpNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpNumberActionPerformed(evt);
            }
        });

        ok.setBackground(new java.awt.Color(0, 204, 255));
        ok.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(0, 204, 255));
        cancel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(otpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addGap(75, 75, 75)
                                .addComponent(ok))
                            .addComponent(jLabel1))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otpNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpNumberActionPerformed
    public void setDataTransfer(int n,int rb,String un,int sb,String un1,int ca,String em,String c)
    {
        this.num = n;
        this.ReceiverBalance = rb;
        this.SenderBalance = sb;
        this.Cre_Amount = ca;
        this.User_name = un;
        this.uname = un1;
        this. email = em;
        this.currency = c;
        this.status = "Transfer";
    }
    public void setDataDebit(int Bal,int Da,String un,String em,int n)
    {
        this.ReceiverBalance=Bal-Da;
        this.temp = Da;
        this.uname = un;
        this.email = em;
        this.num = n;
        this.status = "Debit";
    }
    public void debitData()
    {
        try
        {
            Connection connection=DriverManager.getConnection("jdbc:derby://localhost:1527/Tedo_bank","Zython","Miichan");
            String query = "update ACCOUNT_TRANSACTION set Balance = ? where user_name = ?";
            PreparedStatement stmt= connection.prepareStatement(query);
            stmt.setInt(1,ReceiverBalance);
            stmt.setString(2,uname);
            stmt.executeUpdate();
            Mailer obj=new Mailer();
            String Message="Hi! Amount of Rs."+this.temp+" has been Debited Successfully.\nThanks for Supporting with us.\n\n\t<- Have a Great Day ->\n\nFor Contact (send mail at) :\nzythonencoders@gmail.com";
            obj.send("zythonencoders@gmail.com","SanPanVen302218",email,"Debited Successfully",Message);
            JOptionPane.showMessageDialog(null,"Amount Debited Sucessfully!!");
            Login log=new Login(); 
            log.setVisible(true);
            log.pack();
            log.setLocationRelativeTo(null);
            log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        catch(SQLException exp)
        {
            Logger.getLogger(authentication.class.getName()).log(Level.SEVERE, null, exp);
        }
    }
    public void TransferData()
    {
        try
            {
                Connection connection=DriverManager.getConnection("jdbc:derby://localhost:1527/Tedo_bank","Zython","Miichan");
                Statement stmnt1=connection.createStatement();
                Statement stmnt2=connection.createStatement();

                String query1 = "update ACCOUNT_TRANSACTION set Balance = ? where user_name = ?";
                PreparedStatement stmt1= connection.prepareStatement(query1);
                stmt1.setInt(1,ReceiverBalance);
                stmt1.setString(2,User_name);
                String query2 = "update ACCOUNT_TRANSACTION set Balance = ? where user_name = ?";
                PreparedStatement stmt2= connection.prepareStatement(query2);
                stmt2.setInt(1,SenderBalance);
                stmt2.setString(2,uname);
                stmt1.executeUpdate();
                stmt2.executeUpdate();
                Mailer obj = new Mailer();
                String Message="Hi! Amount of "+Cre_Amount+" "+this.currency+" has been Transfered Successfully to the User : "+User_name+"\nThanks for Supporting with us.\n\n\t<- Have a Great Day ->\n\nFor Contact (send mail at) :\nzythonencoders@gmail.com";
                obj.send("zythonencoders@gmail.com","SanPanVen302218",email,"Debited Successfully",Message);  
                JOptionPane.showMessageDialog(null,"Transfered Sucessfully!!");
            }
            catch (SQLException ex) {
                    Logger.getLogger(Credit.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String otp = otpNumber.getText();
        //System.out.println(Integer.parseInt(otp));
        if(otp.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the OTP number");
        }
        else if(Integer.parseInt(otp) == num)
        {
            if(this.status.equals("Debit"))
            {
                debitData();
            }
            else{
                TransferData();
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid OTP !!");
        }
        Login log=new Login(); 
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authentication().setVisible(true);
                //a.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField otpNumber;
    // End of variables declaration//GEN-END:variables
}
